name: python-setup
run-name: Creating environment to run given script
on:
  workflow_dispatch:
    inputs:
      pythonVersion:
        description: "The version of Python required to run"
        required: true
        default: "3.11"
        type: string
      pythonScript:
        description: "Name of the Python script to run"
        required: true
        type: string
jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{pythonVersion}}
      - run: pip install -r requirements.txt -c constraints.txt
      - run: python ${{pythonScript}}
